server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avillane/repositorioprueba.git
          search-paths: ConfigData
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

  #security:
    #user:
      #name: root
      #password: s3cr3t